[build]
builder = "RAILPACK"
buildCommand = "bun run build"
watchPatterns = ["/frontned/**"]

[deploy]
runtime = "V2"
startCommand = "bun run start"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig."asia-southeast1-eqsg3a"]
numReplicas = 1
