[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
runtime = "V2"
startCommand = "npm run start"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig."asia-southeast1-eqsg3a"]
numReplicas = 1
